# Site settings
title: 'Manish Tuladhar'
description: 'A resume of Manish Tuladhar'

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: 'true'
resume_name: 'Manish Tuladhar'
resume_title: 'Senior Software Engineer'

# used for the contact button in _layouts/resume.html
resume_contact_email: 'manishtuladharwork@gmail.com'

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: '+61-45080943'
resume_contact_address: 'Hurstville, NSW, Australia'

resume_header_contact_info: 'Hurstville, NSW • +61-450809843 • manishtuladharwork@gmail.com'
display_header_contact_info: 'true'

resume_header_intro: '<p>A motivated individual with in-depth knowledge of languages and development tools, seeking a position in a growth-oriented company where I can use my skills to the advantage of the company while having the scope to develop my own skills.</p>'

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: 'yes'

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: 'https://github.com/lighttt'
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: 'https://www.linkedin.com/in/tuladharmanishlight'
  resume_instagram_url: 'https://www.instagram.com/manishtuladhar_'
  # resume_website_url:           "http://manishtuladhar.com.np"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
